name: Build and Publish to Registry

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.13"
          cache: true

      - name: Install dependencies
        run: pdm install --check

      - name: Run tests
        run: pdm run pytest

  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and tag Docker image
        run: docker build .
